### ISSUE TITLE
topic is missing in Trigger Output list

### ISSUE THREAD

**Issue by pauldeng** [project-flogo/edge-contrib#18]
Hi,

I am new to the flogo. Please forgive me if I make naive issue.

**Observed**
topic is listed as one of three output in the readme file of the MQTT trigger. (others are message, topic, topicParams)
I expect all three output parameters should be listed in the trigger configuration of flogo web. However, topic is missing and message and topicParams are there as below.
![issue](https://dengpeng.de/wp-content/uploads/2020/03/flogo_mqtt_trigger_config_issue.png)

**How to reproduce**
- Ubuntu 18.04 in VirtualBox
- Flogo v0.10.1 from docker
- Local MQTT broker mosquito
- Installed  github.com/project-flogo/edge-contrib/trigger/mqtt
- Add topic, message and topicParams as string type in Input Output
- Add and configure the MQTT trigger, switch to Map to flow inputs tab. it shows the screenshot above.

**Question**
Maybe this is not mqtt trigger issue but a flogo web issue. Please let me know, I will create it there.

Thanks.

Cheers,
Paul

**Comment by skothari-tibco** [comment]
Once the above PR is closed; you can re-install the trigger and it would be there.
